"""add mobile_number to users and create profiles

Revision ID: 0befe5cfff10
Revises: 
Create Date: 2026-02-10 00:16:34.087477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0befe5cfff10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 🔥 SAFE DROPS
    op.execute("DROP INDEX IF EXISTS idx_order_events_order_id")
    op.execute("DROP INDEX IF EXISTS idx_orders_buyer_user_id")
    op.execute("DROP INDEX IF EXISTS idx_orders_quote_id")
    op.execute("DROP INDEX IF EXISTS idx_orders_vendor_user_id")
    op.execute("DROP INDEX IF EXISTS idx_rfqs_user_id")
    op.execute("DROP INDEX IF EXISTS ix_users_email")

    # 🔥 ALTERS (safe enough already)
    op.alter_column('rfq_quotes', 'vendor_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    op.alter_column('rfqs', 'required_items',
               existing_type=sa.JSON(),
               nullable=False)

    op.alter_column('rfqs', 'tags',
               existing_type=sa.JSON(),
               nullable=False)

    op.alter_column('rfqs', 'terms',
               existing_type=sa.JSON(),
               nullable=False)

    # 🔥 SAFE CREATES
    op.execute("CREATE INDEX IF NOT EXISTS ix_rfq_quotes_id ON rfq_quotes (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_rfqs_user_id ON rfqs (user_id)")

    # 🔥 ADD COLUMN SAFE
    op.execute("""
        ALTER TABLE users
        ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(32)
    """)

    op.execute("CREATE INDEX IF NOT EXISTS ix_users_email ON users (email)")

    # ⚠️ UNIQUE constraint (no IF NOT EXISTS support → handle manually)
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint 
            WHERE conname = 'uq_users_email'
        ) THEN
            ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email);
        END IF;
    END$$;
    """)

    # 🔥 vendor_profiles
    op.alter_column('vendor_profiles', 'ports_served',
               existing_type=sa.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)

    op.alter_column('vendor_profiles', 'categories_supplied',
               existing_type=sa.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)

    op.execute("CREATE INDEX IF NOT EXISTS ix_vendor_profiles_id ON vendor_profiles (id)")

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint 
            WHERE conrelid = 'vendor_profiles'::regclass 
            AND contype = 'u'
        ) THEN
            ALTER TABLE vendor_profiles ADD CONSTRAINT uq_vendor_profiles_user_id UNIQUE (user_id);
        END IF;
    END$$;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_profiles', type_='unique')
    op.drop_index(op.f('ix_vendor_profiles_id'), table_name='vendor_profiles')
    op.alter_column('vendor_profiles', 'categories_supplied',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('vendor_profiles', 'ports_served',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'mobile_number')
    op.drop_index(op.f('ix_rfqs_user_id'), table_name='rfqs')
    op.create_index('idx_rfqs_user_id', 'rfqs', ['user_id'], unique=False)
    op.alter_column('rfqs', 'terms',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('rfqs', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('rfqs', 'required_items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_rfq_quotes_id'), table_name='rfq_quotes')
    op.alter_column('rfq_quotes', 'vendor_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('idx_orders_vendor_user_id', 'orders', ['vendor_user_id'], unique=False)
    op.create_index('idx_orders_quote_id', 'orders', ['quote_id'], unique=False)
    op.create_index('idx_orders_buyer_user_id', 'orders', ['buyer_user_id'], unique=False)
    op.create_index('idx_order_events_order_id', 'order_events', ['order_id'], unique=False)
    # ### end Alembic commands ###
