"""Add sos_email to crew profile

Revision ID: 1df019db037a
Revises: b616697b9a23
Create Date: 2026-04-08 02:29:50.632473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df019db037a'
down_revision: Union[str, None] = 'b616697b9a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
  op.execute("""
    ALTER TABLE crew_profiles
    ADD COLUMN IF NOT EXISTS sos_email VARCHAR(255)
""")    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew_profiles', 'sos_email')
    # ### end Alembic commands ###
