"""add_port_vessel_to_shore_pass

Revision ID: 56eefdec0624
Revises: 8f4a861acdd0
Create Date: 2026-02-16 21:39:02.411625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56eefdec0624'
down_revision: Union[str, None] = '8f4a861acdd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.execute("DROP INDEX IF EXISTS ix_password_resets_id")
op.execute("DROP INDEX IF EXISTS ix_password_resets_token")
op.execute("DROP TABLE IF EXISTS password_resets")

# 🔥 Safe column adds
op.execute("""
    ALTER TABLE shore_passes
    ADD COLUMN IF NOT EXISTS port_name VARCHAR(128)
""")

op.execute("""
    ALTER TABLE shore_passes
    ADD COLUMN IF NOT EXISTS vessel_name VARCHAR(128)
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shore_passes', 'vessel_name')
    op.drop_column('shore_passes', 'port_name')
    op.create_table('password_resets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_resets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_resets_pkey')
    )
    op.create_index('ix_password_resets_token', 'password_resets', ['token'], unique=False)
    op.create_index('ix_password_resets_id', 'password_resets', ['id'], unique=False)
    # ### end Alembic commands ###
