"""create_shore_passes_table

Revision ID: 8f4a861acdd0
Revises: 0befe5cfff10
Create Date: 2026-02-10 12:28:55.133127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f4a861acdd0'
down_revision: Union[str, None] = '0befe5cfff10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute("""
    CREATE TABLE IF NOT EXISTS shore_passes (
        id SERIAL PRIMARY KEY,
        crew_profile_id INTEGER NOT NULL,
        agent_name VARCHAR(120),
        shore_pass_id VARCHAR(64) NOT NULL UNIQUE,
        out_time TIMESTAMPTZ,
        in_time TIMESTAMPTZ,
        expires_at TIMESTAMPTZ,
        is_verified BOOLEAN,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ,
        FOREIGN KEY (crew_profile_id) REFERENCES crew_profiles(id) ON DELETE CASCADE
    )
    """)

    # ✅ Index
     op.execute("""
    CREATE INDEX IF NOT EXISTS ix_shore_passes_id 
    ON shore_passes (id)
    """)

    # ✅ Safe drops
     op.execute("DROP INDEX IF EXISTS ix_file_assets_id")
     op.execute("DROP TABLE IF EXISTS file_assets")

     op.execute("DROP INDEX IF EXISTS ix_password_resets_id")
     op.execute("DROP INDEX IF EXISTS ix_password_resets_token")
     op.execute("DROP TABLE IF EXISTS password_resets")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_resets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_resets_pkey')
    )
    op.create_index('ix_password_resets_token', 'password_resets', ['token'], unique=False)
    op.create_index('ix_password_resets_id', 'password_resets', ['id'], unique=False)
    op.create_table('file_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='file_assets_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_assets_pkey')
    )
    op.create_index('ix_file_assets_id', 'file_assets', ['id'], unique=False)
    op.drop_index(op.f('ix_shore_passes_id'), table_name='shore_passes')
    op.drop_table('shore_passes')
    # ### end Alembic commands ###
