"""Add chat messages

Revision ID: b616697b9a23
Revises: 56eefdec0624
Create Date: 2026-04-08 02:21:53.938826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b616697b9a23'
down_revision: Union[str, None] = '56eefdec0624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_profiles', 'profile_image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('cab_bookings', 'otp',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=10),
               nullable=True)
    op.add_column('drivers', sa.Column('is_reset_requested', sa.Integer(), server_default='0', nullable=True))
    op.drop_constraint('drivers_hpid_key', 'drivers', type_='unique')
    op.create_index(op.f('ix_drivers_hpid'), 'drivers', ['hpid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_hpid'), table_name='drivers')
    op.create_unique_constraint('drivers_hpid_key', 'drivers', ['hpid'])
    op.drop_column('drivers', 'is_reset_requested')
    op.alter_column('cab_bookings', 'otp',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('agent_profiles', 'profile_image',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
